import { format } from 'date-fns';
import { CATEGORIES, CategoryKey, Segment } from '@/types';
import { escapeICalText } from '@/lib/sanitize';

/**
 * UTILITIES FOR CALENDAR REPRESENTATION & EXPORT
 */

/**
 * Generates a display title by joining unique labels from segments.
 */
export function generateEventTitle(segments: Segment[]): string {
    if (!segments || segments.length === 0) return 'Untitled';

    const labels = Array.from(new Set(
        segments
            .filter(s => s.label !== '_FREE_')
            .map(s => s.label)
            .filter(Boolean)
    ));

    if (labels.length === 0) return 'Untitled';
    return labels.join(' / ');
}

/**
 * Generates a linear gradient string for borders based on segment categories.
 */
export function generateBorderGradient(segments: Segment[]): string {
    if (!segments || segments.length === 0) return CATEGORIES.misc.hex;

    const sorted = [...segments].sort((a, b) => a.offset - b.offset);
    const uniqueCategories = new Set(sorted.map(s => s.category));
    const hasFree = sorted.some(s => s.label === '_FREE_');

    if (uniqueCategories.size === 1 && !hasFree) {
        const cat = sorted[0].category as CategoryKey;
        return CATEGORIES[cat]?.hex || CATEGORIES.misc.hex;
    }

    if (sorted.length === 1) {
        if (sorted[0].label === '_FREE_') return 'transparent';
        const cat = sorted[0].category as CategoryKey;
        return CATEGORIES[cat]?.hex || CATEGORIES.misc.hex;
    }

    let gradient = 'linear-gradient(to bottom, ';
    sorted.forEach((s, i) => {
        const next = (i < sorted.length - 1) ? sorted[i + 1].offset : 60;
        const cat = s.category as CategoryKey;
        const color = s.label === '_FREE_' ? 'transparent' : (CATEGORIES[cat]?.hex || CATEGORIES.misc.hex);

        const startPct = (s.offset / 60) * 100;
        const endPct = (next / 60) * 100;

        gradient += `${color} ${startPct}%, ${color} ${endPct}%${i < sorted.length - 1 ? ', ' : ''}`;
    });
    gradient += ')';

    return gradient;
}

/**
 * Determines the state of the add/edit button for a given hour slot.
 */
export function getButtonState(segments: Segment[]): 'add' | 'edit' {
    if (!segments || segments.length === 0) return 'add';

    const sorted = [...segments].sort((a, b) => a.offset - b.offset);
    let usefulDuration = 0;

    for (let i = 0; i < sorted.length; i++) {
        const seg = sorted[i];
        if (seg.label === '_FREE_') continue;

        const nextOffset = (i < sorted.length - 1) ? sorted[i + 1].offset : 60;
        usefulDuration += (nextOffset - seg.offset);
    }

    if (usefulDuration >= 60 || sorted.length >= 4) {
        return 'edit';
    }

    return 'add';
}

interface CalendarEvent {
    id: string;
    title: string;
    description?: string | null;
    location?: string | null;
    start: Date | string;
    end: Date | string;
}

/**
 * Generates an iCal string from a list of events.
 */
export function generateICal(events: CalendarEvent[]): string {
    const calendarHeader = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//Scheduler//2026//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH'
    ].join('\r\n');

    const calendarFooter = 'END:VCALENDAR';

    const eventStrings = events.map(event => {
        const startStr = new Date(event.start).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
        const endStr = new Date(event.end).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

        return [
            'BEGIN:VEVENT',
            `UID:${event.id}@scheduler.2026`,
            `DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z`,
            `DTSTART:${startStr}`,
            `DTEND:${endStr}`,
            `SUMMARY:${escapeICalText(event.title)}`,
            `DESCRIPTION:${escapeICalText(event.description || '')}`,
            `LOCATION:${escapeICalText(event.location || '')}`,
            'END:VEVENT'
        ].join('\r\n');
    }).join('\r\n');

    return `${calendarHeader}\r\n${eventStrings}\r\n${calendarFooter}`;
}

/**
 * Generates a text summary of the day's events.
 */
export function generateDaySummary(date: Date, events: CalendarEvent[]): string {
    const formattedDate = format(date, 'EEEE, MMM do, yyyy');
    const header = `🌌 SCHEDULER // 2026\nPROTO: NEON-MATRIX\nDATE: ${formattedDate}\n----------------------`;
    const footer = `----------------------\n[ GENERATED BY SCHEDULER // 2026 ]`;

    if (events.length === 0) {
        return `${header}\n// NO TASKS RECORDED\n${footer}`;
    }

    const sortedEvents = [...events].sort((a, b) =>
        new Date(a.start).getTime() - new Date(b.start).getTime()
    );

    const eventLines = sortedEvents.map(event => {
        const time = format(new Date(event.start), 'hh:mm a');
        return `[ ${time} ] ${event.title}`;
    });

    return `${header}\n${eventLines.join('\n')}\n${footer}`;
}
