import { format } from 'date-fns';

interface Event {
    title: string;
    start: string | Date;
    end: string | Date;
    description?: string | null;
    location?: string | null;
    id: string;
}

/**
 * Generates an iCal string from a list of events
 */
export function generateICal(events: Event[]): string {
    const calendarHeader = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//Scheduler//2026//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH'
    ].join('\r\n');

    const calendarFooter = 'END:VCALENDAR';

    const eventStrings = events.map(event => {
        const startStr = new Date(event.start).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
        const endStr = new Date(event.end).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

        return [
            'BEGIN:VEVENT',
            `UID:${event.id}@scheduler.2026`,
            `DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z`,
            `DTSTART:${startStr}`,
            `DTEND:${endStr}`,
            `SUMMARY:${event.title}`,
            `DESCRIPTION:${event.description || ''}`,
            `LOCATION:${event.location || ''}`,
            'END:VEVENT'
        ].join('\r\n');
    }).join('\r\n');

    return `${calendarHeader}\r\n${eventStrings}\r\n${calendarFooter}`;
}

/**
 * Generates a text summary of the day's events for social sharing
 */
export function generateDaySummary(date: Date, events: Event[]): string {
    const formattedDate = format(date, 'EEEE, MMM do, yyyy');
    const header = `🌌 SCHEDULER // 2026\nPROTO: NEON-MATRIX\nDATE: ${formattedDate}\n----------------------`;
    const footer = `----------------------\n[ GENERATED BY SCHEDULER // 2026 ]`;

    if (events.length === 0) {
        return `${header}\n// NO TASKS RECORDED\n${footer}`;
    }

    const sortedEvents = [...events].sort((a, b) =>
        new Date(a.start).getTime() - new Date(b.start).getTime()
    );

    const eventLines = sortedEvents.map(event => {
        const time = format(new Date(event.start), 'hh:mm a');
        return `[ ${time} ] ${event.title}`;
    });

    return `${header}\n${eventLines.join('\n')}\n${footer}`;
}
